language: node_js
node_js:
  - "0.10"
  - 0.12
  - iojs
before_install:
  - npm install -g grunt-cli
notifications:
  email:
    - jwells@titleio.com
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
